open-cluster-management-io/governance-policy-framework-addon

- Makefile
- README.md
- main.go
- tool/options.go
When running on the Hub, spec-sync controller should be disabled since the replicated policies are already present on the Hub from the Policy Propagator.
Relates:
https://github.com/stolostron/backlog/issues/25999 https://github.com/stolostron/backlog/issues/25949
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Add an option to disable the spec-sync controller

- controllers/templatesync/template_sync.go
Without this, the dependencies never get cleaned up when they are entirely removed. Additionally, if the policy had no dependencies, it would error since that is invalid input to AddOrUpdateWatcher.
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Handle when a policy doesn't have dependencies

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- main.go
- test/e2e/case12_ordering_test.go
- test/resources/case12_ordering/case12-dependency-b.yaml
- test/resources/case12_ordering/case12-dependency.yaml
- test/resources/case12_ordering/case12-plc-2-template.yaml
- test/resources/case12_ordering/case12-plc-multiple-deps.yaml
- test/resources/case12_ordering/case12-plc.yaml
Adds logic to determine whether a policy template should be pending based on whether its dependencies are satisfied. If a template should be pending, these changes will remove it from the managed cluster and set the status of the parent policy to Pending.
https://github.com/stolostron/backlog/issues/26188
https://github.com/stolostron/backlog/issues/26189
> Set pending state on policies if dependencies are not met + remove template

- main.go
This bug caused the /healthz endpoint on the proxy to combine the controller
manager's /readyz endpoints. This would lead to the controller not
restarting when the Hub kubeconfig changed.
Relates:
https://issues.redhat.com/browse/ACM-1932
> Fix a bug where the /healthz endpoint pointed to underlying /readyz

- controllers/templatesync/template_sync.go
- test/e2e/case12_ordering_test.go
changes the list of failed dependencies in the status from just "namespace.name" to "kind namespace.name" to make the status message more clear
Signed-off-by: Will Kutler <wkutler@redhat.com>
> add kind to pending status

- controllers/templatesync/template_sync.go
- test/e2e/case12_ordering_test.go
- test/resources/case12_ordering/case12-plc-invalid-dep.yaml
Signed-off-by: Will Kutler <wkutler@redhat.com>
Previously we were generating violations on mapping errors for dependencies (ex: wrong API group for a dependency). @JustinKuli and I decided this was a bit confusing for users, since the NonCompliant status generated by this error gives the impression that the dependency passed and the policy generated a violation, rather than the other way around. This change makes all mapping errors show the same Pending status as dependencies that are correctly formatted but do not exist.
> emit pending on mapping error

- .github/workflows/kind.yml
- README.md
- controllers/templatesync/template_sync.go
- test/e2e/case4_status_merge_test.go
Based on comments in https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/15, dependencies should generally have a blank namespace. Then the controller will know to use the cluster namespace. But without the main commit here, the namespace was not present in this situation when creating the watches with `kubernetes-dependency-watches` library, which meant that the watches weren't correctly created.
Other commits address some CI failures.
> Clusternamespace for dep watches

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- test/e2e/case12_ordering_test.go
- test/resources/case12_ordering/case12-plc-ignorepending.yaml
Previously, individual templates were always marked as "Pending" if they
had an unsatisfied dependency. The `ignorePending` field was only
considered when calculating the overall compliance of a Policy. But that
meant that it was not possible to correctly calculate the overall state
with just the status object, which is confusing.
Now, the `ignorePending` field is considered when marking the compliance
of each template. This makes how the overall compliance is calculated
more clear, and the new messages may be more helpful for users.
Refs:
- https://issues.redhat.com/browse/ACM-2101
> Handle ignorePending differently

- README.md
> Add OCM doc link

- controllers/templatesync/template_sync.go
- main.go
- test/e2e/case13_metrics_test.go
- tool/options.go
By default, the metrics are exposed at localhost:8383. Note that this means in a pod, workloads outside the pod *can not* access them.
Refs:
- https://issues.redhat.com/browse/ACM-2179
Also includes a minor improvement to logs for dependencies.
> Expose metrics

- go.mod
- go.sum
Relates:
https://issues.redhat.com/browse/ACM-2485
> Update kubernetes-dependency-watches to v0.1.1

- controllers/templatesync/template_sync.go
- test/e2e/case10_error_test.go
- test/e2e/case11_status_ts_collision_test.go
- test/e2e/case12_ordering_test.go
- test/e2e/case14_user_metrics_test.go
- test/e2e/case1_mutation_recovery_test.go
- test/e2e/case2_status_sync_test.go
- test/e2e/case3_multiple_templates_test.go
- test/e2e/case4_status_merge_test.go
- test/e2e/case5_error_handling_test.go
- test/e2e/case6_event_msg_test.go
- test/e2e/case7_spec_sync_test.go
- test/e2e/case8_sync_secret_test.go
- test/e2e/case9_template_sync_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case10_template_sync_error_test/working-policy-configpol.yaml
Some refactoring as well, but the more important bit is this commit:
Previously, if a Policy defined a template that already exists, it assumed that another Policy had defined it, and tried to get its owner reference in order to give a helpful error message. But if the template was created outside of a Policy, then this process would panic.
Refs:
- https://issues.redhat.com/browse/ACM-3416
> Unowned template panic

- controllers/templatesync/template_sync.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
- main.go
- test/e2e/case15_template_cleanup_test.go
- test/resources/case15_template_cleanup/case15-config-policy-rename.yaml
- test/resources/case15_template_cleanup/case15-config-policy-stable.yaml
- test/resources/case15_template_cleanup/case15-test-policy-patch-delete.yaml
- test/resources/case15_template_cleanup/case15-test-policy-patch-rename.yaml
- test/resources/case15_template_cleanup/case15-test-policy.yaml
Adds a label to policy templates that are created as a child of a policy, then compares the policy templates actually contained in that policy to all templates with the parent policy label to determine if templates have been renamed or removed from the parent. The template sync will then clean up any policy templates that are not being managed by the parent policy that created them.
refs:
- https://issues.redhat.com/browse/ACM-3049?filter=-1
Signed-off-by: Will Kutler <wkutler@redhat.com>
> Clean up policy templates that have been removed from the parent policy

- controllers/templatesync/template_sync.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/28 added get and list permissions for CRDs, but only list is used. This PR updates the cluster role so it doesn't have the extra get permission.
> Remove get permission for CRDs

- controllers/templatesync/template_sync.go
- test/e2e/case16_restore_owner_refs_test.go
- test/resources/case16_restore_owner_refs/case16-patch-configpolicy.yaml
- test/resources/case16_restore_owner_refs/case16-test-policy.yaml
Previously if the owner references array was removed from the metadata of a policy template, there was no way to recoveer them. With recent commits this no longer caused an index out of bounds panic, but we still want to keep the owner references, so this PR adds code to restore them if they are removed.
refs: https://issues.redhat.com/browse/ACM-3027
> Recover owner references that are removed from policy templates

- controllers/templatesync/template_sync.go
- test/e2e/case15_template_cleanup_test.go
- test/resources/case15_template_cleanup/case15-patchlabel.yaml
Currently, the parent policy label on templates, which is used for https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/28 , is only set on template creation, which could cause issues with policies that have already been created. This fix verifies the necessary template labels are set when updating the template. It also includes a light refactor of the template equality check to make it look a little cleaner.
> Set parent policy label on template when updating

- Makefile
- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/gatekeepersync/health.go
- controllers/gatekeepersync/policy_predicate.go
- controllers/utils/events.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
- main.go
- test/e2e/case17_gatekeeper_sync_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case17_gatekeeper_sync/case17-gk-constraint.yaml
- test/resources/case17_gatekeeper_sync/case17-gk-policy-extra.yaml
- test/resources/case17_gatekeeper_sync/case17-gk-policy.yaml
- test/resources/case17_gatekeeper_sync/case17constrainttemplate.yaml
- test/utils/common.go
This controller is responsible for relaying Gatekeeper constraint audit results as policy status events for constraints associated with a policy.
The controller will only start if Gatekeeper is installed. If Gatekeeper's installation status changes while the controller manager is running, the health endpoint will return as unhealthy to cause Kubernetes to restart the pod to then enable/disable this new controller.
Relates:
https://issues.redhat.com/browse/ACM-3328
> Add the Gatekeeper constraint status sync controller

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
The SHA1 hashes are used for uniqueness checks in a cache. They are not used for anything security related.
> Ignore gosec failures for SHA1 usage

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/templatesync/template_sync.go
- controllers/utils/utils.go
- test/e2e/case12_ordering_test.go
- test/e2e/case17_gatekeeper_sync_test.go
- test/e2e/e2e_suite_test.go
This commit changes the discovery REST mapper that was used to be targeted to
that specific resource version.
This is to reduce load on the Kubernetes API as well as to reduce the chance
of long delays due to queries per second (QPS) exceeding the default limit.
An additional commit was added to prevent watches being created on Gatekeeper constraints without the corresponding CRD installed.
Other commits are to address flaky tests.
Relates:
https://issues.redhat.com/browse/ACM-4518
> Perform discovery API calls only as needed

- go.mod
- go.sum
This will reduce the number of API calls for discovery.
Relates:
https://issues.redhat.com/browse/ACM-4518
> Update the dependency watch client

- go.mod
- go.sum
- main.go
Relates:
https://issues.redhat.com/browse/ACM-4588
> Disable the Gatekeeper controller when run in old Kubernetes clusters

- controllers/templatesync/template_sync.go
Listing Gatekeeper Constraints was refreshing the discovery API. This adds a global boolean to only attempt cleanup when a Constraint was previously synced successfully.
> Conditionally clean up Gatekeeper Constraints

- .github/workflows/kind.yml
- Makefile
- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/secretsync/secret_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- controllers/uninstall/triggeruninstall.go
- controllers/uninstall/watcher.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
- main.go
- test/e2e/case18_uninstall_test.go
- test/resources/case18_uninstall/case18-gk-policy-updated.yaml
- test/resources/case18_uninstall/case18-gk-policy.yaml
A new "controller" watches the Deployment for an uninstall annotation. When the annotation is true, it updates a flag so that all the other controllers don't have to track it individually. Most controllers just skip their reconciles during the uninstall, but the template-sync will clean up its finalizers (and skip an error case during that process).
The default behavior is still to run the controllers. But if the first command line argument is `trigger-uninstall`, then the process will add the uninstallation annotation to the controller's deployment, and delete all the policies on the cluster. The main intent of this is to be run as a pre-delete hook when uninstalling the addon.
https://issues.redhat.com/browse/ACM-3329
> 3329 finalizer cleanup

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
- go.mod
- go.sum
When it's already reset or is empty, the patch fails and leads to the reconcile request being retried until the corresponding controller that provides status for the policy template.
Relates:
https://issues.redhat.com/browse/ACM-4486
> Stop resetting the policy template compliance when already reset

- controllers/templatesync/template_sync.go
- test/e2e/case10_error_test.go
- test/resources/case10_template_sync_error_test/multiple-obj-template-arrays.yaml
Replaces the error returned by the CRD for conflicting object-templates and object-templates-raw with a more readable one. There does not seem to be a way to add a custom error message for this failure in the CRD itself, so this change just watches for the error message and replaces it with a more readable one before the event is sent.
ref: https://issues.redhat.com/browse/ACM-4083
> Make conflicted object template error more readable

- controllers/uninstall/watcher.go
- deploy/manager/manager.yaml
- deploy/operator.yaml
- tool/options.go
The environment variable will be populated from the labels on the pod, using the downward API.
Refs:
- https://issues.redhat.com/browse/ACM-3329
Fixes problems found in https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/71, where the deployment name is different [in the addon-controller](https://github.com/open-cluster-management-io/governance-policy-addon-controller/blob/cce56fadef78a48b33524d1c99888de59c7ec7d7/pkg/addon/policyframework/manifests/managedclusterchart/templates/deployment.yaml#L6) than here... Looking back, hard-coding it here was not the best idea I've ever had.
> Get deployment name from environment variable

- controllers/templatesync/template_sync.go
The situation this is meant to fix is not fully understood. But in case a policy template that was previously pending somehow has some status that has not yet made its way into the Policy's status, this will reset it, so that the policy controller knows to send a new compliance event.
Refs:
- https://issues.redhat.com/browse/ACM-4699
> Reset the complianceState when Pending

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/templatesync/template_sync.go
- controllers/utils/events.go
- main.go
- test/e2e/case12_ordering_test.go
Main commit:
Previously, the controller-runtime event recorder was used for these events. Other policy controllers have moved away from that, for various reasons. In this case, if a policy went from pending to noncompliant and back to pending, the "old" pending event would be re-used by the event recorder, and only the `lastTimestamp` would be updated. In this case, if a policy controller emitted a compliance event within the same second as the Pending event, the status-sync would see it as a tie, and use the hex-encoded nanoseconds in the event name. But the event name was not updated from the original instance when the policy was pending, so the events would be ordered incorrectly.
Most error cases from this synchronous sending can be ignored because they are already error cases that …
> Synchronously emit template events

- .github/workflows/kind.yml
- Makefile
- controllers/templatesync/template_sync.go
- test/e2e/case17_gatekeeper_sync_test.go
Fixes some issues identified by GoSec, and incorporates the scan into CI here so it will fail when other issues are found.
> GoSec fixes and improvements

- controllers/utils/events.go
Description of problem:
The status message for non compliant policy is truncated with "..." when the policy has multiple objectTemplates or a namespace. This leaves the user unable to determine why the policy is non compliant.
Expect result:
Messges should not be truncated. Messages can be over 1024 in length
> Bug: Policy compliance status is truncated

- controllers/templatesync/predicate.go
- controllers/templatesync/template_sync.go
- test/e2e/case12_ordering_test.go
Previously, if the policy controller sent out a compliance event after the policy transitioned to a Pending state (because things are async), that compliance event would override the Pending state, and might never be corrected. Now, the template-sync should re-reconcile in that case, and apply the Pending state again.
Refs:
- https://issues.redhat.com/browse/ACM-5022
> Correct to Pending status after late events

- controllers/statussync/policy_status_sync.go
for the global hub, we are going to show the policy compliance trend. It is very important to have real policy status in the events so that we can know the frequency of policy changing.
@mprahl Is the change OK? Thanks.
> Update event to include real status

- .github/workflows/go-release.yml
I foolishly removed it not thinking about the Makefile, but this should make its use clearer.
Followup to:
- #66
> Add back `TAG` to release workflow

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_utils.go
- test/e2e/case10_error_test.go
- test/resources/case10_template_sync_error_test/dup-name-policy.yaml
Creating a policy with identical names succeeds. The ConfigurationPolicy is repeatedly overwritten by the template-sync, swapping out the two policies, and repeatedly updating the status with alternating statuses from the two policies.
For example, this policy has two ConfigurationPolicy templates both named policy-pod
Expect to fail and return a status that there is a duplicate name instead.
Ref: https://issues.redhat.com/browse/ACM-5724
Signed-off-by: Yi Rae Kim <yikim@redhat.com>
> Bug: Creating two policy templates with the same name succeeds

- deploy/operator.yaml
- deploy/rbac/leader_election_role.yaml
ConfigMap permissions were only necessary for legacy leader election, which was removed.
ref: https://issues.redhat.com/browse/ACM-5042
> Remove ConfigMap permissions

- controllers/templatesync/template_sync.go
- test/e2e/case20_informonly_test.go
- test/resources/case20_policy_informonly/case20-parent-policy-noremediation.yaml
- test/resources/case20_policy_informonly/case20-parent-policy.yaml
Overrides the parent policy's remediationAction when 'informonly' is provided as the remediationAction for ConfigurationPolicy
> Allow informonly configuration policies

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/secretsync/secret_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- controllers/uninstall/watcher.go
Previously, the running container could only move *into* uninstallation mode - once it was in that mode, it needed to be restarted to restore normal operations. To improve the reliability of uninstall/reinstall scenarios, it can now move back into normal operations automatically.
All reconciles that were skipped during uninstallation are now just delayed 5 minutes. A "normal" uninstallation should be completed within that amount of time. If the uninstallation was aborted, then this should ensure no reconciles are permanently missed.
Refs:
- https://issues.redhat.com/browse/ACM-6941
> Allow uninstall mode to be cancelled

- controllers/templatesync/template_sync.go
- test/e2e/case21_syntax_error_metric_test.go
- test/resources/case21_syntax_error_metric/case21-test-policy-err.yaml
- test/resources/case21_syntax_error_metric/case21-test-policy.yaml
**Description of problem:** Currently, when a user provides an invalid policy template and the API call fails due to a syntax issue (for example, a ConfigurationPolicy containing a syntax error), the metric policy_system_errors_total increments instead of policy_user_errors_total. This causes false positive system level health check alerts.
**Solution:** Added simple checks for syntax errors to determine whether to increment user or system error metrics
**Ref:** https://issues.redhat.com/browse/ACM-3160
> ACM-3160: Invalid policy-templates array syntax leads to policy_system_errors_total incrementing

- controllers/templatesync/template_sync.go
- test/e2e/case10_error_test.go
ref: https://issues.redhat.com/browse/ACM-6346
> Remove duplicated compliance in Gatekeeper synced policy message

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
We don't want duplicate config policy templates, but the logic prevented me from having a Constraint and a ConstraintTemplate that had the same name.  Of course a config policy couldn't have that same name either so adding gvk in the name check.
Refs:
- https://issues.redhat.com/browse/ACM-7265
> Fix template sync duplicate detection

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- test/e2e/case22_user_validation_error_test.go
- test/resources/case22_user_validation_error/case22-test-correct.yaml
- test/resources/case22_user_validation_error/case22-test-err.yaml
Description of problem: A policy with a user error is not validated, and the policy does not become `NonCompliant` (it actually stays `Compliant`). This is because the code in the policy status sync controller completely skips of all other templates once it is unable to decode a template. If no other previously evaluated templates were `NonCompliant`, then the entire policy becomes `Compliant`.
Solution:
- In the template sync controller, template names were changed from `[template %v]` format to `template-%v` in order to fit with the regex in the policy status sync controller.
- The policy status sync controller was changed to not `break` when unable to read a template and instead to continue evaluating while setting the policy to `NonCompliant`.
Ref: …
> Bug: ACM-6803, Incorrect Policy does not show any validation errors and no status

- controllers/templatesync/template_sync.go
After updating to controller-runtime 0.15, it seems that a different error is returned when a CRD is missing, so it caused an API server hit every time the policy template sync controller reconciled. This uses the new error.
Relates:
https://github.com/stolostron/backlog/issues/27375
> Adjust the error to check for the ConstraintTemplate CRD missing

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- test/e2e/case10_error_test.go
- test/resources/case10_template_sync_error_test/invalid-name-error.yaml
If an invalid character is provided in a template name, our RegEx was filtering it out and not handling it properly.
I'm not sure whether this is too broad and we might need something like non-whitespace `^\s` or non-forward-slash `^/`, but technically a user can put whatever they want in there, so it seemed like `.` might be most appropriate.
ref: https://issues.redhat.com/browse/ACM-7737
> Fix RegEx to allow any character in a template name

- deploy/manager/kustomization.yaml
- deploy/manager/manager.yaml
- deploy/operator.yaml
This is used for debug log collection by the framework.
Reverts change in https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/51
/cc @JustinKuli
> Add back name label to deployment

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
The template name duplications could be an issue with users managing lots of templates and there being a requirement no names can conflict. To avoid having duplicate names there would need to be additional fields in the status which I don't want to add unless we have a customer RFE. This update removes a previous change.
Refs:
- https://issues.redhat.com/browse/ACM-7265
- https://issues.redhat.com/browse/ACM-7566
> Undo the template duplication check update

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/secretsync/secret_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- main.go
- tool/options.go
To allow configuration for concurrent reconciles, QPS, and burst, the following changes are proposed:
- Each reconciler struct for all controllers will require an extra field called `ConcurrentReconciles`, which is exposed in main and set to the value specified in the arguments passed to the framework addon.
- The `ConcurrentReconcile` field will be used when the set up between controller and manager occurs
-  QPS and burst are also parsed from controller arguments passed to the framework addon, and override default QPS and burst values from controller-runtime after the hub and managed configs are created.
ref: https://issues.redhat.com/browse/ACM-6711
> Enable concurrent reconciles, QPS, and burst configurations

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/secretsync/secret_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/eventMapper.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
I was looking at this for ACM-7778, but I don't think that the logs here are particularly noisy - since the controller is event driven, knowing when it starts reconciling something (for example) can be quite useful. Instead, this PR just ensures that the controller's log messages are consistently formatted.
> Update log calls to be more consistent

- test/e2e/case22_user_validation_error_test.go
Hit a panic with "index out of bounds". Also bumps the length of the Details array to the correct threshold.
ref: https://github.com/stolostron/governance-policy-framework-addon/actions/runs/6809803804/job/18516791082?pr=207
> Fix test panic

- main.go
When --disable-spec-sync is set to true, the hub manager is set to nil. Currently, this is not detected when setting up the controllers, which causes a seg fault when referencing the nil hub manager. In addition to fixing the behaviour, a new cache will be created on the hub for the case where the hub manager, and subsequently, the related hub manager cache, is not set.
ref: https://issues.redhat.com/browse/ACM-6869
> fix nil reference when hub-only controllers are disabled

- main.go
Some previous change seems to have removed the case to parse the congif when the managed-cluster-configfile argument is specified.
> Prevent panic when using the managed-cluster-configfile argument

- .github/workflows/kind.yml
- Makefile
- build/common/Makefile.common.mk
- controllers/secretsync/secret_sync.go
- controllers/uninstall/triggeruninstall.go
- deploy/hubpermissions/kustomization.yaml
- deploy/operator.yaml
- deploy/rbac/role.yaml
- deploy/rbac/service_account.yaml
- test/e2e/e2e_suite_test.go
- test/resources/e2e_controller_secret.yaml
Changes:
- Create service accounts and related resources on both the hub and managed cluster
- Create separate kubeconfig files to be used for the controller and E2E tests
- Utilize the common makefile when bootstrapping clusters
ref: https://issues.redhat.com/browse/ACM-3301
> Use SA for E2E

- controllers/templatesync/template_sync.go
- test/e2e/case17_gatekeeper_sync_test.go
- test/resources/case17_gatekeeper_sync/case17-gk-dep-on-constraint.yaml
- test/resources/case17_gatekeeper_sync/case17-gk-dep-on-tmpl.yaml
Originally, policy dependencies could only handle objects that had a `status.complianceState` field. Gatekeeper ConstraintTemplates and Constraints do not have this field, but we assign them a compliance in a similar way elsewhere. This commit allows these Gatekeeper types to be used for policy dependencies like a user might expect.
Refs:
- https://issues.redhat.com/browse/ACM-8998
> Handle policy dependencies of Gatekeeper types

- controllers/templatesync/template_sync.go
It's unclear what package upgrade prompted this change, however, the existing error detection no longer worked when running on OpenShift 3.11.
For further context, this is the error this is now detecting:
https://github.com/kubernetes-sigs/controller-runtime/blob/6747c42ce33966b0e77cac278c6b9087cc2f51c7/pkg/client/apiutil/restmapper.go#L189-L194
Relates:
https://issues.redhat.com/browse/ACM-9533
> Update the error to detect when the server only has v1beta1 CRDs

- Makefile
- controllers/secretsync/secret_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- main.go
- test/e2e/case10_error_test.go
- test/resources/case10_template_sync_error_test/missing-kind.yaml
If the Kind is missing after decoding the JSON, we shouldn't be requeuing since this is not recoverable.
(Yes, the E2E YAML is from real life 🤦)
Also updates the Makefile (since we synced it without taking the time to clean up the repo one).
ref: https://issues.redhat.com/browse/ACM-9844
> Fix requeue when Kind is missing

- controllers/statussync/policy_status_sync.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
- test/e2e/case23_compliance_api_recording_test.go
Related to https://github.com/open-cluster-management-io/governance-policy-addon-controller/pull/133
The addon framework's hub kubeconfig is certificate based. This does not allow authentication to the compliance history API using an OpenShift route that handles the TLS. Because of this, token based authentication is required.
This uses the hub kubeconfig's token first and if not set, falls back to getting the token from a secret in the cluster namespace on the Hub created by the policy addon controller.
Relates:
https://issues.redhat.com/browse/ACM-6889
> Use token authentication for the compliance history API

- controllers/statussync/policy_status_sync.go
This is to account for the database IDs being invalid due to data loss in the database. This is not recoverable so stop retrying forever.
Relates:
https://issues.redhat.com/browse/ACM-10109
> Stop retrying to record invalid compliance events

- controllers/statussync/policy_status_sync.go
- controllers/statussync/policy_status_sync_test.go
- test/e2e/case23_compliance_api_recording_test.go
This helps with ordering when compliance events have a timestamp that is the same down to the second.
Relates:
https://issues.redhat.com/browse/ACM-10155
> Record compliance events in the compliance history API with nanoseconds

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- test/e2e/case23_compliance_api_recording_test.go
- test/resources/case23_compliance_api_recording/policy3.yaml
The template-sync was not providing the policy template to SendEvent, so
the compliance history database ID annotations could not be added to the
Kubernetes compliance event.
This resolves the issue of not having compliance events related to a
Gatekeeper ConstraintTemplate being created successfully.
> Record template-sync compliance events in compliance history API

- .github/workflows/framework-kind.yml
- Makefile
ref: https://issues.redhat.com/browse/ACM-4811
> Run framework tests on OCM PRs

- controllers/templatesync/template_sync.go
Bug: If the template-sync is shutting down and it's in the middle of a reconcile request, it can set the policy to noncompliant with this
Ref: https://issues.redhat.com/browse/ACM-10402
> Fix template sync set to Nomcompliant when context cancel

- controllers/complianceeventssync/disabled_events_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- main.go
Note, this is the related PR in the propagator: https://github.com/open-cluster-management-io/governance-policy-propagator/pull/215
There were issues with duplicated compliance events and having a different code path in the governance-policy-propagator for a self-managed hub. This will unifies the approaches.
It takes the approach of using a retry watcher and just generating the disabled event when the policy is deleted. The controller-runtime library cannot be used because when there is a reconcile event for a deleted object, you don't have access to the object as it was right before deletion.
Relates:
https://issues.redhat.com/browse/ACM-10418
> Move the disabled events recording outside of spec-sync

- Makefile
This fixes the debug log collection when an E2E test fails in the GitHub workflow.
Relates:
https://issues.redhat.com/browse/ACM-11200
> Use the admin kubeconfig for the e2e-debug Make target

- Makefile
- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- main.go
The first commit updates the E2E environment Gatekeeper to 3.15 and uses the Stolostron fork.
This also improves the situation when the ConstraintTemplate is removed and the policy still deploys a Constraint.
Relates:
https://issues.redhat.com/browse/ACM-11200
> Use the dependency watcher cache in gatekeeper-constraint-status-sync

- main.go
Since the controller no longer restarts when the Gatekeeper installation state changes, we need to prevent controller-runtime from creating a watch on constraint templates, or else the client-go watcher will continuously log errors trying to restart the watch.
Relates:
https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/134
> Bypass the caching of constraint templates

- controllers/statussync/policy_status_sync.go
- controllers/templatesync/predicate.go
- controllers/templatesync/template_sync.go
- test/e2e/case10_error_test.go
- test/e2e/case22_user_validation_error_test.go
- test/resources/case10_template_sync_error_test/error-hubtemplate.yaml
It appears that "special" compliance events related to template-errors can potentially be superseded by later events coming from a policy controller. Specifically, if a template is valid and gets created, but is later edited to have an error, the original template is not removed. Because undesired side-effects could be caused by removing a template (eg PruneObjectBehavior in a ConfigurationPolicy), it would be risky to "fix" this by removing the template in this situation. Instead, this PR proposes that the template-sync always re-reconcile after the status is updated, which allows it to correct the "late" event by emitting a new template-error.
The increased number of reconciles does increase the possibility of duplicate compliance events. Accordingly, some tests have been relaxed, and …
> Handle template errors better

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
- test/e2e/case10_error_test.go
The noncompliant event was sent in this case but the status-sync did not pick it up because it specified the policy template name using the array index.
Relates:
https://issues.redhat.com/browse/ACM-11806
> Set the parent policy to NonCompliant when there is a duplicate name

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
equivalentTemplates should correctly apply complianceConfig defaults. The complianceConfig PR: https://github.com/open-cluster-management-io/config-policy-controller/pull/252
Ref:https://issues.redhat.com/browse/ACM-11023
> Modify equivalentTemplates for OperatorPolicy complianceConfig defaults

- test/e2e/case10_error_test.go
Previously, the CRD did not validate the status.compliance field on ConfigurationPolicies, but now it does. The test will now use, and check for, an allowed value on that field.
> Use a valid compliance state in a test

- deploy/rbac/auth_cluster_role.yaml
- deploy/rbac/auth_cluster_role_binding.yaml
- deploy/rbac/metrics_reader.yaml
- go.mod
- go.sum
- main.go
- tool/options.go
Use the new `FilterProvider` and `SecureServing` fields to authenticate and authorize requests to the metrics endpoint
ref: https://issues.redhat.com/browse/ACM-8346
> Use controller-runtime to protect metrics endpoint

- controllers/templatesync/template_sync.go
- test/e2e/case12_ordering_test.go
- test/resources/case12_ordering/case12-plc-nonexist-dep.yaml
This version of the dependency-watches library can panic if passed duplicate object IDs along with an object ID for a kind that is not present on the cluster. This avoids triggering that situation, and might be easier to backport than changes to the library itself.
Refs:
- https://issues.redhat.com/browse/ACM-14091
> De-duplicate objects to watch

- controllers/templatesync/template_sync.go
It doesn't make sense to have a "missing CRD" message attached to any particular reconcile. For example, the log currently appears as this, which is confusing since the policy isn't a Gatekeeper policy:
```
2024-11-26T23:57:44.964Z
info
policy-template-sync
templatesync/template_sync.go:1157
The ConstraintTemplate CRD is not installed
{"Request.Namespace": "<namespace>", "Request.Name": "<policy-namespace>.<policy-name>"}
```
> Detach ConstraintTemplate CRD log from a policy

- controllers/templatesync/template_sync.go
- test/e2e/case9_template_sync_test.go
- test/resources/case9_template_sync/case9-test-policy-with-ns.yaml
Previously, if the user set a namespace in the template, then when the template-sync tried to create the template, it would fail. Now the template-sync always uses the cluster namespace, overriding what the user might have provided.
Refs:
- https://issues.redhat.com/browse/ACM-17666
> Override the namespace set in the template

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
Previously, the template and the existing resource had to have exactly matching labels and annotations. But in some cases, external controllers might add a new label or annotation, which this controller would see as a mismatch. Now it just ensures that the desired labels and annotations exist and match.
Refs:
- https://issues.redhat.com/browse/ACM-21219
> Relax equivalence on template metadata

- Makefile
- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- main.go
- test/e2e/e2e_suite_test.go
Previously, when Gatekeeper was uninstalled, the context for the gatekeeper sync manager was permanently cancelled. As a result, if Gatekeeper was re-installed, the manager would immediately stop again, and the constraint-sync controlelr would not be started properly.
Refs:
- https://issues.redhat.com/browse/ACM-21861
> Fix restarting the gatekeeper-constraint-sync
