- controllers/statussync/policy_status_sync.go
- test/e2e/case11_status_ts_collision_test.go
- test/e2e/case1_mutation_recovery_test.go
- test/e2e/case2_status_sync_test.go
- test/e2e/case3_multiple_templates_test.go
- test/e2e/case6_event_msg_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case11_ts_collision/case11-event-five.yaml
- test/resources/case11_ts_collision/case11-event-four.yaml
- test/resources/case11_ts_collision/case11-event-one.yaml
- test/resources/case11_ts_collision/case11-event-six.yaml
- test/resources/case11_ts_collision/case11-event-three.yaml
- test/resources/case11_ts_collision/case11-event-two.yaml
- test/resources/case11_ts_collision/case11-policy.yaml
Brings in the changes from:
- https://github.com/open-cluster-management-io/governance-policy-status-sync/pull/36
- https://github.com/open-cluster-management-io/governance-policy-status-sync/pull/37
But in fewer commits, because it was done right the first time here.
> Better event sorting

- main.go
Relates:
https://github.com/stolostron/backlog/issues/25999
Signed-off-by: mprahl <mprahl@users.noreply.github.com>
> Set the namespace to watch

- build/Dockerfile
- go.mod
- tool/operator-sdk-port.go
ref: 
- https://github.com/stolostron/backlog/issues/26059
> Update to Go 1.19

- controllers/templatesync/template_sync.go
- deploy/operator.yaml
- deploy/rbac/role.yaml
fixes cache error that was introduced by https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/28
> Add watch for CRD to role

- controllers/templatesync/template_sync.go
This will prevent unnecessary reconciles for dependency updates after the policy that defined the dependencies is deleted.
> Remove the dependency watches when a policy is deleted

- controllers/statussync/policy_status_sync.go
Hopefully minimize these errors:
```
2023-03-17T19:40:36.831Z	error	policy-status-sync	statussync/policy_status_sync.go:401	Failed to get update policy status on hub	{"Request.Namespace": "local-cluster", "Request.Name": "policy-test.policy-gatekeeper-operator", "HubNamespace": "local-cluster", "error": "Operation cannot be fulfilled on policies.policy.open-cluster-management.io \"policy-test.policy-gatekeeper-operator\": the object has been modified; please apply your changes to the latest version and try again"}
open-cluster-management.io/governance-policy-framework-addon/controllers/statussync.(*PolicyReconciler).Reconcile
/go/src/github.com/open-cluster-management-io/governance-policy-framework-addon/controllers/statussync/policy_status_sync.go:401 …
```
> Re-fetch the hub policy prior to sending an update

- controllers/templatesync/template_sync.go
equivalentTemplates would always return false when a ConfigurationPolicy was encountered without pruneObjectBehavior explicitly set since the Kubernetes API returns "None" as the default value.
This isn't an ideal solution, but it's inexpensive compared to performing API queries to see what defaults are and this is a common case.
> Stop updating on every reconcile when pruneObjectBehavior is not set

- .github/workflows/kind.yml
- controllers/templatesync/template_sync.go
- main.go
- main_test.go
- test/e2e/case17_gatekeeper_sync_test.go
- test/e2e/case19_gatekeeper_disable_test.go
- test/e2e/e2e_suite_test.go
- test/resources/case19_gatekeeper_disable/case19-gk-policy.yaml
- tool/options.go
ref: https://issues.redhat.com/browse/ACM-4444
> Add flag to disable Gatekeeper sync

- controllers/templatesync/template_sync.go
On older versions of k8s where the v1 version of CRDs is not available, this method was preventing the controller from working.
Refs:
- https://issues.redhat.com/browse/ACM-5326
> Check v1beta1 CRD for policy template label

- controllers/uninstall/triggeruninstall.go
ref: https://issues.redhat.com/browse/ACM-5632
> Bind logs to make uninstall logging work

- Makefile
- build/Dockerfile
- build/common/scripts/gobuild.sh
> Stop explicitly disabling CGO

- main.go
This removes all unnecessary fields in an Event object before it is cached. Additionally, a field selector is added to avoid caching events unrelated to policy compliance.
Relates:
https://issues.redhat.com/browse/ACM-6063
> Reduce memory utilization of caching events

- controllers/templatesync/template_sync.go
- test/e2e/case20_informonly_test.go
- test/resources/case20_policy_informonly/case20-parent-policy.yaml
- test/resources/case20_policy_informonly/case20-policy-template-noremediation.yaml
https://issues.redhat.com/browse/ACM-6632
> Bug: ACM-6632, parent policy cannot override remediationAction if unset in policy template

- Makefile
These are set by the framework, but overwritten when applying the `operator.yaml`.
ref: https://issues.redhat.com/browse/ACM-4873
> Patch args when redeploying controller

- main.go
Setting up the controller after both the Hub and Managed managers are created allows "indirect" clients to be passed to the controllers' reconcile function. These "indirect" clients are able to read from the cache configured by each of the managers.
ref: https://issues.redhat.com/browse/ACM-6869
> Refactor controller set up logic to expose cache access

- build/Dockerfile
- go.mod
- go.sum
ref: https://issues.redhat.com/browse/ACM-9734
> Update to Go v1.21

- controllers/gatekeepersync/gatekeeper_constraint_sync.go
- controllers/specsync/policy_spec_sync.go
- controllers/statussync/policy_status_sync.go
- controllers/templatesync/template_sync.go
- main.go
See each commit for details.
Relates:
https://issues.redhat.com/browse/ACM-10500
https://issues.redhat.com/browse/ACM-10403
> Various stability fixes and reduce log noise

- controllers/specsync/policy_spec_sync.go
Relates:
https://issues.redhat.com/browse/ACM-10418
> Prevent duplicate disabled compliance events

- .gitignore
- .vscode/launch.json
Relates:
https://issues.redhat.com/browse/ACM-10885
> Add a launch.json for local development

- controllers/templatesync/template_sync.go
Updating controller-runtime seems to have changed the error.
Relates:
https://issues.redhat.com/browse/ACM-11498
> Detect the correct error for resource not found

- controllers/templatesync/template_sync.go
- controllers/templatesync/template_sync_test.go
Relates:
https://issues.redhat.com/browse/ACM-11846
> Handle the default value for recreateOption

- build/Dockerfile
- go.mod
ref: https://issues.redhat.com/browse/ACM-14251
> Update to Go v1.22

- Makefile
- controllers/templatesync/template_sync.go
- test/e2e/case17_gatekeeper_sync_test.go
- test/resources/case17_gatekeeper_sync/error-status/policy.yaml
ConstraintTemplate is created and compliant even with invalid rego syntax
Ref: https://issues.redhat.com/browse/ACM-15588
> Fix ConstraintTemplate creation with invalid rego

- build/Dockerfile
- go.mod
- go.sum
> Address `oauth2` vuln
